name: dart_desktop_dev-building_executable_files
run-name: ${{ github.actor }} - dart_desktop_dev-building_executable_files
on:
  workflow_dispatch:
env:
  flutter_channel: stable
  working_directory: dart_desktop_dev
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build linux
        working-directory: ${{ env.working_directory }}
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build windows
        working-directory: ${{ env.working_directory }}
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter build macos
        working-directory: ${{ env.working_directory }}