name: dart_common_dev-running_unit_tests
run-name: ${{ github.actor }} - dart_common_dev-running_unit_tests
on:
  push:
    branches:
      - lastpolukrovka
env:
  flutter_channel: stable
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.flutter_channel }}
      - run: flutter pub get
        working-directory: dart_common_dev
  ## build
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: flutter test
        working-directory: dart_common_dev